### ISSUE TITLE
Ensimmäinen koodikatselmointi

### ISSUE THREAD

**Issue by AuroraLS3** [niklasad/Kniffel#1]
Repo versio ladattu: 7facf5d1651bfbf94525acfe99e1f4b83249f89d
Ladattu klo _**19:45** 30.03.2017_

### Virheitä koodissa:
```
Heittovuoro:17  pelaaja = pelaaja; //this.pelaaja
```
### Testit
toStringToimii testi epäonnistui (testissä kirjoitusvirhe):
```
expected:<pelaaja1, piste[]t: 0> but was:<pelaaja1, piste[e]t: 0>
org.junit.ComparisonFailure
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at kniffel.pelaaja.PelaajaTest.toStringToimii(PelaajaTest.java:86)
	...
```
### Muuta huomioitavaa:

Luokka | Koodi | Kommentti
-------- | -------- | --------
Poytakirja:21 | this.pisteet = new HashMap<String, Integer>(); | Timantti operaattoria voidaan käyttää [HashMap<>()]
Poytakirja:77 | int pisteet = 0; | Saman niminen muuttuja kuin saman luokan private HashMap<String, Integer> pisteet;
Poytakirja:89 | int pisteet; | Saman niminen muuttuja kuin saman luokan private HashMap<String, Integer> pisteet;
Poytakirja:86-104 | samojenloytaja metodi | käytetään List<Noppa>.contains(int)
Poytakirja:76 | pisteLaskuri metodi | Pisteet lasketaan "uudelleen" mikäli tulos luokkaa on käytetty.
Poytakirja ja Tulos luokat |  | Logiikka noppien tunnistukseen on periaatteessa luotu kahdesti

#### Tulos 
 Koska luokkaa käytetään pohjaluokkana muille `logiikka.tulokset` paketin luokille, kannattaa se muuttaa abstraktiksi. (`public abstract class`)

 **kayta metodi**
  Jos muutat luokan abstraktiksi tämä metodi kannattaa muuttaa muotoon `public abstract void metodi(parametrit);`. Testasin ja Netbeans ei ainakaan valittanut muutoksesta.
  kayta metodin parametrina on `List<Integer>` ja Heittovuorossa käytetään `List<Noppa>`. Alla olevalla koodinpätkällä nopat voi muuttaa luvuiksi nopeasti.
 ```
List<Integer> silmaluvut = nopat.stream().map(noppa -> noppa.silmaluku()).collect(Collectors.toList());
```

Kun nopat on heitetty kerran pelaaKierros() metodilla, kaikkien noppien `boolean lukittu` on true. Kannattaa jossain vaiheessa nollata lukitus (vaikka Heittovuoron konstruktorissa "alussa").

On Poytakirja ja Pelaaja - molemmilla on pisteet, en tiedä tuleeko Pelaaja omistamaan Poytakirja tyyppisen olion. Tällöin pisteet voidaan laskea Poytakirjan pisteet.values() avulla.

Luokat ovat järkevästi rakennettu. Tykkäsin erityisesti siitä että uuden heittovuoron voi aloittaa 
`new Heittovuoro` tyyliin

Rupesin miettimään tulos luokkien määrää katsellessa että olisiko niitä voinut mahdollisesti luoda yhdellä Enum luokalla. En keksinyt tähän hätään pikaista ratkaisua jonka logiikka olisi ollut helppo kirjoittaa. 

Saa kysyä, jos on kysymyksiä.
Jätän hautumaan. :)

**Comment by AuroraLS3** [comment]
Pahoittelen, näköjään päivitit sillävälin kun kirjoitin palautetta.
Todennäköisesti korjasit osan palautteessa mainituista asioista.
kommentoin lisää palautetta huomenna tai lauantaina tuosta uudesta versiosta jonka latasit.

**Comment by AuroraLS3** [comment]
Repo versio: 5db682c47c28f04a341682f03367a46caa59fba3
Ladattu **14.49** 31.03.2017

### Virheitä koodissa
Sama kuin versiossa 7facf5d  `Heittovuoro:15  pelaaja = pelaaja;`

### Testit
Kaikki testit menivät läpi Windows systeemillä.

### Palautetta / Muuta huomioitavaa

Hyvä että pistelaskenta on siirretty omaan luokkaansa.
Copy-paste koodi pisteenlaskennasta on hienosti poistettu käyttämällä kolmea metodia.
Ei muuta lisättävää.
